#ifndef BOTTLES_H
#define BOTTLES_H

const char* PYD_bottles[] =
{
    "Vuoto",
    "Aperol",
    "Assenzio",
    "Bourbon Whiskey",
    "Brandy",
    "Cachaca",
    "Campari",
    "Champagne",
    "Cognac",
    "Cola",
    "Cynar",
    "Gin",
    "Ginger Ale",
    "Ginger Beer",
    "Grappa Alla Pesca",
    "Kirsch",
    "Lager",
    "Latte Di Cocco",
    "Lemon Soda",
    "Lillet Blonde",
    "Limonata",
    "Liquore Al Caffè",
    "Mezcal",
    "Pisco",
    "Prosecco",
    "Rum Bianco",
    "Rum Scuro",
    "Rye Whiskey",
    "Sciroppo Di Lampone",
    "Sciroppo Di Zucchero",
    "Scotch Whisky",
    "Soda",
    "Succo D'Ananas",
    "Succo D'Arancia",
    "Succo Di Lampone",
    "Succo Di Lime",
    "Succo Di Limone",
    "Succo Di Mirtilli Rossi",
    "Succo Di Pesca",
    "Succo Di Pompelmo",
    "Tequila",
    "Tonica",
    "Triple Sec",
    "Vermouth Rosso",
    "Vodka",
    "Whiskey"
};

#endif /* BOTTLES_H */