#define STEPPER1_PIN_STEP 2
#define STEPPER1_PIN_DIRECTION  15
#define STEPPER1_PIN_ENABLE 27
#define STEPPER1_PIN_ENDSTOP 35
#define STEPPER1_ENDSTOP_ACTIVE_LOW 0       // 0 or 1
#define STEPPER1_REVERSE_DIRECTION true    // true or false
#define STEPPER1_SPEED_IN_HZ 1600
#define STEPPER1_ACCELERATION 1000

#define SERVO_PIN 25