name: "Build Channel Commit"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Arduino CLI
      run: |
        sudo apt-get update --quiet
        sudo apt-get install --assume-yes --no-install-recommends --quiet bash bash-completion ca-certificates curl python-is-python3 python3 python3-pip ssh tree
        sudo pip install adafruit-nrfutil pyserial
        cd /usr && sudo curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sudo sh -s ${ARDUINO_CLI_VERSION}
        arduino-cli config init 
        arduino-cli core update-index
        arduino-cli core install esp32:esp32@2.0.17
        arduino-cli lib install "ArduinoMenu library"@4.21.4
        arduino-cli lib install QDEC@2.1.0
        arduino-cli lib install FastAccelStepper@0.30.14
        arduino-cli lib install ESP32Servo@3.0.5
        cd ~/Arduino/libraries && git clone https://github.com/fmalpartida/New-LiquidCrystal
    - name: Compile
      run: arduino-cli compile -b esp32:esp32:esp32doit-devkit-v1 --output-dir build
    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: build.bin
        path: build/cocktail-machine.ino.bin
        retention-days: 5
    - name: Upload Build to Releases
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/cocktail-machine.ino.bin
        asset_name: build.bin
        tag: ${{ github.ref }}-push
        overwrite: true
        body: "Build for commit ${{ github.sha }}"