name: "Build New Release"
on:
  release:
    types: [ "published" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Arduino
      run: make install
    - name: Compile
      run: make BUILD_VERSION=${{github.event.release.tag_name}} build
    - name: Upload Build to Releases
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      run: |
        apt-get install -y gh
        cp build/cocktail-machine.ino.bin build.bin
        gh release upload ${{github.event.release.tag_name}} build.bin